version: '3.8'

services:

#Go to http://localhost:3000 and Add your Supabase PostgreSQL database by selecting "PostgreSQL" as the database type and entering the connection details (host, database, username, password, etc.).
#Once the database details are entered, they are retained even if the container restarts.

  metabase:
    image: metabase/metabase:latest
    container_name: supabase-metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db # This is the default internal H2 database location.
      # Optional: If you prefer to use Postgres for Metabase's internal database, uncomment the lines below:
      # MB_DB_TYPE: postgres
      # MB_DB_DBNAME: ${POSTGRES_DB}
      # MB_DB_PORT: ${POSTGRES_PORT}
      # MB_DB_USER: ${POSTGRES_USER}
      # MB_DB_PASS: ${POSTGRES_PASSWORD}
      # MB_DB_HOST: ${POSTGRES_HOST}
    volumes:
      - ./metabase-data:/metabase-data
    restart: always

  # Optional: If you want to run a PostgreSQL database for Metabase's internal data:
  # postgres:
  #   image: postgres:latest
  #   container_name: metabase-postgres
  #   environment:
  #     POSTGRES_USER: your_metabase_user
  #     POSTGRES_PASSWORD: your_metabase_password
  #     POSTGRES_DB: metabase_internal_db
  #   volumes:
  #     - ./metabase-postgres-data:/var/lib/postgresql/data
  #   restart: always

# Optional: You could add a supabase container if you are self-hosting supabase
# For now, Supabase PostgreSQL is external, so not included in this file.
